"use client";

import { useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";
import jsPDF from "jspdf";

interface PDFExportProps {
    title: string;
    content: string;
}

export default function PDFExport({ title, content }: PDFExportProps) {
    const handleExport = useCallback(() => {
        const pdf = new jsPDF();
        const pageWidth = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const margin = 20;
        const maxWidth = pageWidth - 2 * margin;
        let yPosition = margin;

        // Title
        pdf.setFontSize(18);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(180, 83, 9); // Amber color
        pdf.text("LawAssist AI - Legal Solution", margin, yPosition);
        yPosition += 12;

        // Case title
        pdf.setFontSize(14);
        pdf.setTextColor(0, 0, 0);
        pdf.text(title, margin, yPosition);
        yPosition += 10;

        // Date
        pdf.setFontSize(10);
        pdf.setTextColor(100, 100, 100);
        pdf.text(`Generated on: ${new Date().toLocaleDateString("en-IN")}`, margin, yPosition);
        yPosition += 10;

        // Separator line
        pdf.setDrawColor(180, 83, 9);
        pdf.line(margin, yPosition, pageWidth - margin, yPosition);
        yPosition += 10;

        // Content
        pdf.setFontSize(11);
        pdf.setTextColor(0, 0, 0);
        pdf.setFont("helvetica", "normal");

        // Split content into lines
        const lines = content.split("\n");

        lines.forEach((line) => {
            // Check for headers
            if (line.startsWith("# ")) {
                yPosition += 5;
                pdf.setFontSize(16);
                pdf.setFont("helvetica", "bold");
                pdf.setTextColor(180, 83, 9);
                const headerText = line.replace(/^# /, "");
                const wrappedHeader = pdf.splitTextToSize(headerText, maxWidth);
                wrappedHeader.forEach((headerLine: string) => {
                    if (yPosition > pageHeight - margin) {
                        pdf.addPage();
                        yPosition = margin;
                    }
                    pdf.text(headerLine, margin, yPosition);
                    yPosition += 8;
                });
                pdf.setFontSize(11);
                pdf.setFont("helvetica", "normal");
                pdf.setTextColor(0, 0, 0);
            } else if (line.startsWith("## ")) {
                yPosition += 4;
                pdf.setFontSize(13);
                pdf.setFont("helvetica", "bold");
                pdf.setTextColor(60, 60, 60);
                const headerText = line.replace(/^## /, "");
                const wrappedHeader = pdf.splitTextToSize(headerText, maxWidth);
                wrappedHeader.forEach((headerLine: string) => {
                    if (yPosition > pageHeight - margin) {
                        pdf.addPage();
                        yPosition = margin;
                    }
                    pdf.text(headerLine, margin, yPosition);
                    yPosition += 7;
                });
                pdf.setFontSize(11);
                pdf.setFont("helvetica", "normal");
                pdf.setTextColor(0, 0, 0);
            } else if (line.startsWith("- ")) {
                const bulletText = line.replace(/^- /, "• ");
                const wrappedBullet = pdf.splitTextToSize(bulletText, maxWidth - 5);
                wrappedBullet.forEach((bulletLine: string, index: number) => {
                    if (yPosition > pageHeight - margin) {
                        pdf.addPage();
                        yPosition = margin;
                    }
                    pdf.text(bulletLine, margin + (index === 0 ? 0 : 5), yPosition);
                    yPosition += 6;
                });
            } else if (line.trim() === "") {
                yPosition += 3;
            } else {
                const wrappedText = pdf.splitTextToSize(line, maxWidth);
                wrappedText.forEach((textLine: string) => {
                    if (yPosition > pageHeight - margin) {
                        pdf.addPage();
                        yPosition = margin;
                    }
                    pdf.text(textLine, margin, yPosition);
                    yPosition += 6;
                });
            }
        });

        // Footer
        const totalPages = pdf.getNumberOfPages();
        for (let i = 1; i <= totalPages; i++) {
            pdf.setPage(i);
            pdf.setFontSize(8);
            pdf.setTextColor(150, 150, 150);
            pdf.text(
                `Page ${i} of ${totalPages} | Generated by LawAssist AI`,
                margin,
                pageHeight - 10
            );
        }

        // Save PDF
        const fileName = `LawAssist-${title.substring(0, 30).replace(/[^a-zA-Z0-9]/g, "-")}.pdf`;
        pdf.save(fileName);
    }, [title, content]);

    return (
        <Button
            onClick={handleExport}
            className="bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-600 hover:to-orange-700 text-white shadow-lg"
        >
            <Download className="w-4 h-4 mr-2" />
            Export as PDF
        </Button>
    );
}
